name: Deploy Projects

on:
  push:
    branches:
      - master

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_projects: ${{ steps.detect_changes.outputs.changed_projects }}
      skip_deploy: ${{ steps.detect_changes.outputs.skip_deploy }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Detect changed Projects
        id: detect_changes
        run: |
          chmod +x scripts/detect-changes.sh
          ./scripts/detect-changes.sh

      - name: test1
        run: echo ${cat $GITHUB_OUTPUT}


  deploy:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ !needs.detect-changes.outputs.skip_deploy }}
    strategy:
      matrix:
        project: ${{ fromJson(needs.detect-changes.outputs.changed_projects) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build Projects
        run: |
          chmod +x scripts/build-projects.sh
          ./scripts/build-projects.sh

      - name: Deploy changed Projects
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: ${{ matrix.project }}
